// import { Link } from "react-router-dom";
// import ResponsiveAppBar from "../components/nav";
// import LOGO from '../logo.svg';
// const Page2 = () => {
//     return (
//         <>
//             <ResponsiveAppBar />
//         <div id="main-card2">
        
    
//             {/* <div className='bottomControls'>
//                 <button className='btn btn-1 btn-spacing'><Link to="/">Home</Link></button>
//                 <button className='btn btn-2 btn-spacing'><Link to="/about">About</Link></button>
//                 <button className='btn btn-3 btn-spacing'><Link to="/contact">Contact</Link></button>
//                 <button className='btn btn-3 btn-spacing'><Link to="/subscribe">Subscribe</Link></button>
//             </div> */}
//         </div>
//         </>
//     )
// };
// export default Page2;
import * as React from 'react';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import ResponsiveAppBar from '../components/nav';
import { blue } from '@mui/material/colors';

export default function MediaCard() {
  return (
    <>
    <ResponsiveAppBar/>

    <Card sx={{ maxWidth: 100000 , marginTop:10 ,height:400,}}>

      <CardContent>
        <Typography gutterBottom variant="h2" sx={{ fontSize: 40 }} component="div">
        What is DoubtFree?

        </Typography>
        <Typography variant="body2" color="black" sx={{ fontSize: 20 ,}}>
        DoubtFree is a question and answer website where people go to find information. Every piece of content on the site is generated by users, meaning it is created, edited, and organized by the same people that use the website.
        </Typography>
        <Typography variant="body2" color="black" sx={{ fontSize: 20 ,}}>
        It allows users to create social networks and follow topics that interest them. 
It focuses on high-quality questions and answers. 
It enable users to vote on answers to highlight the most accurate information possible.
        </Typography>
        <Typography variant="body2" color="black" sx={{ fontSize: 20 ,}}>
        DoubtFree can be the first step in building that kind of word-of-mouth popularity.
        </Typography>
      </CardContent>
    </Card>
    </>
  );
}

